const Links = [
    {
        id:'array-1',
        topic:'Array',
        link:'https://dev.to/mmvergara/javascript-tagalog-arrays-4haj',
        author:'MMVergara',
    },
    {
        id:'tdz-1',
        topic:'Temporal Dead Zone',
        link:'https://dev.to/mmvergara/javascript-tagalog-temporal-dead-zone-tdz-3344',
        author:'MMVergara',
    },
    {
        id:'ternary-operator-1',
        topic:'Ternary Operator',
        link:'https://dev.to/mmvergara/javascript-tagalog-ternary-operator-2c0g/',
        author:'MMVergara',
    },
    {
        id:'optiona-chaining-1',
        topic:'Optional Chaining',
        link:'https://dev.to/mmvergara/javascript-tagalog-optional-chaining-464p',
        author:'MMVergara',
    },
    {
        id:'let-1',
        topic:'Let Variable',
        link:'https://dev.to/mmvergara/javascript-tagalog-let-variable-declaration-2l5',
        author:'MMVergara',
    },
    {
        id:'const-1',
        topic:'Const Variable',
        link:'https://dev.to/mmvergara/javascript-tagalog-const-variable-declaration-218m',
        author:'MMVergara',
    },
    {
        id:'arrow-fn-1',
        topic:'Arrow Function',
        link:'https://dev.to/mmvergara/javascript-tagalog-arrow-function-1gc9',
        author:'MMVergara',
    },
    {
        id:'nco-1',
        topic:'Nullish Coalescing Operator',
        link:'https://dev.to/mmvergara/javascript-tagalog-nullish-coalescing-operator-1gkl',
        author:'MMVergara',
    },
    {
        id:'break-1',
        topic:'Break Statement',
        link:'https://dev.to/mmvergara/javascript-tagalog-break-statement-1ghc',
        author:'MMVergara',
    },
    {
		id:'undefined-1',
        topic:"Undefined",
        link:"https://dev.to/mmvergara/javascript-tagalog-undefined-44ic",
        author:"MMVergara",
    },
    {
		id:'null-1',
        topic:"Null",
        link:"https://dev.to/mmvergara/javascript-tagalog-null-4mo3",
        author:"MMVergara",
    },
    {
		id:'boolean-1',
        topic:"Boolean",
        link:"https://dev.to/mmvergara/javascript-tagalog-boolean-4i5k",
        author:"MMVergara",
    },
    {
		id:'strings-1',
        topic:"Strings",
        link:"https://dev.to/mmvergara/javascript-tagalog-strings-2ee0",
        author:"MMVergara",
    },
    {
		id:'alert-1',
        topic:"Alert",
        link:"https://dev.to/mmvergara/javascript-tagalog-alert-5a98",
        author:"MMVergara",
    },
    {
		id:'forof-1',
        topic:"for of loop",
        link:"https://dev.to/mmvergara/javascript-tagalog-for-of-loop-1898",
        author:"MMVergara",
    },
    {	
		id:'equality-1',
        topic:"Equality",
        link:"https://dev.to/mmvergara/javascript-tagalog-equality-strict-equality-2med",
        author:"MMVergara",
    },
    {	
		id:'strict-equality-1',
        topic:"Strict Equality",
        link:"https://dev.to/mmvergara/javascript-tagalog-equality-strict-equality-2med",
        author:"MMVergara",
    },
    {	
		id:"fn-decl-1",
        topic:"Function Declaration",
        link:"https://dev.to/mmvergara/javascript-tagalog-function-declaration-43ng",
        author:"MMVergara",
    },
    {	
		id:"fn-expr-1",
        topic:"Function Expression",
        link:"https://dev.to/mmvergara/javascript-tagalog-function-expression-4969",
        author:"MMVergara",
    },
    {	
		id:"pop-arr-method-1",
        topic:"pop - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-array-pop-method-16bh",
        author:"MMVergara",
    },
    {	
		id:"push-arr-method-1",
        topic:"Push - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-array-push-method-296",
        author:"MMVergara",
    },
    {	
		id:"reverse-arr-method-1",
        topic:"Reverse - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-array-reverse-method-4bi8",
        author:"MMVergara",
    },
    {	
		id:"shift-arr-method-1",
        topic:"Shift - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-array-shift-method-5bnl",
        author:"MMVergara",
    },
    {	
		id:"unshift-arr-method-1",
        topic:"Unshift - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-array-unshift-method-3ogg",
        author:"MMVergara",
    },
    {	
		id:"concat-arr-method-1",
        topic:"Concat - Array Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-concat-array-method-1m49",
        author:"MMVergara",
    },
    {	
		id:"startswith-str-method-1",
        topic:"startsWith - String Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-string-startswith-method-1ipj",
        author:"MMVergara",
    },
    {	
		id:"endswith-str-method-1",
        topic:"endsWith - String Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-string-endswith-method-4eel",
        author:"MMVergara",
    },
    {	
		id:"padstart-str-method-1",
        topic:"padStart - String Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-string-padstart-method-jpn",
        author:"MMVergara",
    },
    {	
		id:"padend-str-method-1",
        topic:"padEnd - String Method",
        link:"https://dev.to/mmvergara/javascript-tagalog-string-padend-method-4ki4",
        author:"MMVergara",
    },

]
export default Links;